### ISSUE TITLE
The "filename" option is required to use "extends" with "relative" paths

### ISSUE THREAD

**Issue by comerc** [pbastowski/meteor-jade-templates#1]
example code from [here](http://jade-lang.com/reference/extends/) 

solution described [here](http://stackoverflow.com/questions/27248343/jade-the-filename-option-is-required-to-use-extends-with-relative-paths)

**Comment by comerc** [comment]
same problem for `include` example code from [here](http://jade-lang.com/reference/includes/)

**Comment by comerc** [comment]
solution for meteor [here](https://github.com/meteorwebcomponents/synthesis/pull/9)

**Comment by pbastowski** [comment]
Thanks.
