### ISSUE TITLE
Usage with Urigo/angular-meteor

### ISSUE THREAD

**Issue by netopolit** [pbastowski/meteor-jade-templates#4]
Hi,
Is there a way to use the plugin with https://github.com/Urigo/angular-meteor ? I cloned the Meteor Angular 2 example app (https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping) to try out meteor-jade-templates. I replaced one of the html templates with jade template but it doesn't seem to work. I get errors like this one  `client/imports/app/parties/parties-list.compo
nent.ts (5, 22): Cannot find module './parties-list.component.jade'.`

Thank you.

**Comment by pbastowski** [comment]
Hi @netopolit 

You can use the Atmosphere package `pbastowski:jade-templates` with any language or framework, because it simply converts templates into text. To use this package with ng1 or ng2, you first add it tp your project (perhaps you've done this already?):

```
meteor add pbastowski:jade-templates
```

Then, in your TS file follow this pattern:

``` js
import { Component } from '@angular/core'

@Component({
    selector:    'my-component',
    template:    require('./app.jade'),
})

export class MyComponent {
}
```

> The above assumes that you are using TypeScript and ES6 modules in your Meteor project.

If the above does not help, then please provide a link to your repo in github that replicates the problem and I will have a look at it for you.

**Comment by netopolit** [comment]
Thank you. It does work with require. This is enough for me but if you have time I'm curious why it doesn't work if I try to import jade file like this:

```
import { Component } from "@angular/core";
import template from "./app.component.jade";
import style from "./app.component.scss";

@Component({
  selector: "app",
  template,
  styles: [ style ]
})
export class AppComponent {
  constructor() {
  }
}
```

I've forked a basic angular2-meteor example repo and replaced app.component.html with a jade file.
https://github.com/netopolit/angular2-meteor-base.

**Comment by pbastowski** [comment]
Sorry, I tried, but it can't be fixed. Babel and TypeScript handle default exports (module.exports) so differently that unfortunately you will have to require the jade templates. On the bright side, it saves you one variable ;)

**Comment by netopolit** [comment]
Requiring is just fine. Happy to be able to use jade easily in this stack. Thanks for your effort!
